### PR TITLE
Breaking: drop supporting node 4.x

### PR DESCRIPTION
**Pull request by Aladdin-ADD**

### CODE REVIEW

**Comment by platinumazure** [comment]
Should we cut a major release here and then consume in ESLint? Is there anything else we should consider that might be a breaking change here?

**Comment by j-f1** [comment]
> Is there anything else we should consider that might be a breaking change here?

How about converting some of the code to ES6 constructs?

**Comment by platinumazure** [comment]
> How about converting some of the code to ES6 constructs?

Good call @j-f1, although we could (and probably should) make those changes in patch/minor releases after the major release. I was more thinking, are there any breaking changes we should make to the API that would improve usability or address other issues, which we should include with the major release along with dropping support for Node 4?

**Comment by kaicataldo** [comment]
Ah, sorry - I totally missed this PR! I'm going to close this since I just merged https://github.com/eslint/doctrine/pull/223.

**Pull request closed without merging**
