### PR TITLE
fix: Allow array indexes in names

### LINKED ISSUE #192: Permitting numeric keys in parameter names
**What version are you using?**

2.0.0

**What JSDoc comment were you trying to parse?**

```js
/**
 * This tests our support for iterator rest inside an
 * iterator destructure (RestElement)
 *
 * @param {Array} input
 * @param {any} input.0 head of iterator
 * @param {any[]} ...input.xs body of iterator
 *
 * @returns {any[]} rotated such that the last element was the first
 */
```

**What Doctrine options were you using (sloppy, unwrap, etc.)?**

```js
var result = doctrine.parse(comment, {
    // have doctrine itself remove the comment asterisks from content
    unwrap: true,
    // enable parsing of optional parameters in brackets, JSDoc3 style
    sloppy: true,
    // `recoverable: true` is the only way to get error information out
    recoverable: true,
    // include line numbers
    lineNumbers: true
  });
```

**What happened? Include output if possible.**

The parsed tag for `input.0` is

```js
        {
            "title": "param",
            "description": "0 head of iterator",
            "type": {
                "type": "NameExpression",
                "name": "any"
            },
            "name": "input.null"
        },
```

Note that `input.0` is transformed to `input.null` because of [this clause in the parameter name parser](https://github.com/eslint/doctrine/blob/46c600f27f54b3ab6b0b8a9ac9f97c807ffa95ef/lib/doctrine.js#L304-L306) which ensures that parts of parameter names are either `[]` or valid JavaScript identifiers, and `0` is not a valid identifier.

**What did you expect to happen?**

I expected `input.0` to be parsed verbatim, with `0` serving as an array index. I can confirm that JSDoc's allows this syntax:

image

---

Happy to provide a PR allowing for this syntax - I'm not sure if it'll be removing the `isIdentifierStartES5` code or if there's something else required to avoid regressions.

### PR DESCRIPTION
**Pull request by tmcw**
Fixes #192 by allowing numeric identifiers in `scanIdentifier`

### CODE REVIEW

**Comment by tmcw** [comment]
@nzakas I'd be happy to help review & merge PRs if you're interested in extra help on the doctrine side!

**Comment by ilyavolodin** [comment]
@tmcw Sorry about huge delay in responding. Most of ESLint team is not very familiar with doctrine. We could definitely use some help with reviewing PRs.

**Comment by kaicataldo** [comment]
@tmcw Is this something you'd still be interested in?

**Comment by tmcw** [comment]
Yep, can someone grant me the ability to do reviews / merge etc?

**Comment by bptremblay** [comment]
I’m looking for the emoji for gratitude!

**Comment by tmcw** [comment]
👍 Thanks!

**Pull request merged**
