### PR TITLE
Fix: fixing line numbers

### LINKED ISSUE #138: Reported line numbers are sometimes incorrect
```
let comment = `
/**
 * Test class
 * @extends {BaseClass}
 * @constructor
 * @param {string} name
 */
`;

doctrine.parse(comment, {unwrap: true, lineNumbers: true});


{ description: '/**\nTest class',
  tags: 
   [ { title: 'extends',
       description: null,
       lineNumber: 3,
       type: [Object],
       name: null },
     { title: 'constructor',
       description: null,
       lineNumber: 5,
       type: null,
       name: null },
     { title: 'param',
       description: '/',
       lineNumber: 7,
       type: [Object],
       name: 'name' } ] }
```

Constructor's lineNumber is 5, but should be 4. 
Param's lineNumber is 7. Should be 5

Also, notice the param's description.

### PR DESCRIPTION
**Pull request by TEHEK**
Fixes #138

Replacing skip when parsing tags.

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks, can you please take a moment to read over our contribution guidelines and update your PR? http://eslint.org/docs/developer-guide/contributing/pull-requests

**Comment by TEHEK** [comment]
The lint passes, CLA signed. Anything else?

**Comment by nzakas** [comment]
Travis is failing, also, the commit message format.

**Comment by TEHEK** [comment]
"Fixing issue where input was not consumed via `advance()` but was skipped when parsing tags resulting in sometimes incorrect reported `lineNumber`."

I think travis was failing at master's HEAD when cloned:
https://travis-ci.org/eslint/doctrine/jobs/91032202

**Comment by TEHEK** [comment]
This looks like some sort of a lint error:
lib/typed.js
  line 923  col 14  'parseTypeExpression' was used before it was defined.
  line 995  col 14  'parseTop' was used before it was defined.

But i can't reproduce it locally. npm test and npm run lint are green...

**Comment by nzakas** [comment]
The commit message should have "(fixes #138)" at the end.

Looks like you're right about Travis. If you can update the commit message, I'll merge.

**Comment by TEHEK** [comment]
Updated the commit message. Please verify it's ok :)

**Comment by nzakas** [comment]
Sorry, still not correct. I don't mean to be nitpicking, it's just that our tools key off of this format.

Try "Fix: line numbers for some tags (fixes #138)" as the commit summary. You can put any additional info you want on the following lines. 

More info: http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

**Comment by TEHEK** [comment]
Sure, no problem! I somehow missed that step.

Updated.

**Comment by nzakas** [comment]
Thanks so much for your patience

**Comment by TEHEK** [comment]
Thanks for the quick release! I was about to ask when the fix will be available :)

**Pull request merged**
