### PR TITLE
Allow slash and dash in name as namepath

### PR DESCRIPTION
**Pull request by morlay**
Just a quick fix for #100.
not sure, is this ok enough.

### CODE REVIEW

**Comment by gyandeeps** [comment]
@morlay Can you also add a unit test for dashes please?

**Comment by morlay** [comment]
@gyandeeps unit test for dash is added.  
But still not sure, has Constellation plan to fix this ? :-(

**Comment by gyandeeps** [comment]
@nzakas This looks good.

**Comment by nzakas** [comment]
@morlay Thanks for the PR. Can you also sign our CLA? http://eslint.org/cla

We'll be following ESLint pull request conventions from now on, so can you squash your commits into one and prefix your commit message with "Fix:"? Thanks

**Comment by gyandeeps** [comment]
@morlay Are you still working on this?

**Comment by morlay** [comment]
@gyandeeps 
Sorry, heavy work recently.  
Updated

**Comment by BYK** [comment]
This also fixes #116.

**Comment by nzakas** [comment]
I think there's a bug in this code. It seems to allow `foo----bar`, which I believe is invalid.

**Comment by BYK** [comment]
@morlay - are you still working on this?

**Comment by morlay** [comment]
@BYK 
Sorry, other heavy things need to focus. could you help to continue this ?

**Comment by bobholt** [comment]
@nzakas Are you aware of any documentation on restricting things like `foo----bar`. It definitely makes sense, but I'd like to offer a patch to @morlay's PR, and want to make sure it covers any other similar restrictions.

**Comment by nzakas** [comment]
Actually, i don't believe `-` is allowed at all. There can be one `:`, and multiple `/`. See http://usejsdoc.org/about-namepaths.html

**Comment by bobholt** [comment]
Thanks @nzakas. That looks to be true as the `-` can signify an inner member in JSDOC 2. I'll update my PR to @morlay.

**Comment by gyandeeps** [comment]
Guys any update here ?
CC: @bobholt @morlay

**Comment by nzakas** [comment]
I think we need to go back to the drawing board on this.

**Pull request closed without merging**
