### PR TITLE
Add a fallback to the list of monospace fonts

### PR DESCRIPTION
**Pull request by j-f1**
Right now, I see this:

variable-width serif code

### CODE REVIEW

**Comment by j-f1** [comment]
@platinumazure Should I fix the commit message?

**Comment by platinumazure** [comment]
Yes please. I think "Chore:" would probably be the best prefix (technically this is a docs change but it's more behind the scenes rather than changing content). Thanks!

**Comment by j-f1** [comment]
Fixed @platinumazure!

**Comment by platinumazure** [comment]
Thanks for contributing, @j-f1!

**Pull request merged**
